services:
  pacha_app:
    container_name: pacha_app
    image: pee-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://192.168.100.236:5432/proyecto
      - DATABASE_USERNAME=app_user
      - DATABASE_PASSWORD=123456
